name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "배포 환경을 선택해주세요."
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  actions: read # This is required for slack

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Preview

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Set environment variables
        run: |
          echo "VERCEL_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Build Project Artifacts
        run: |
          if [[ ${{ env.VERCEL_ENV }} == "production" ]]; then
            vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
          else 
            vercel --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Discord Webhook Action
        if: ${{ env.VERCEL_ENV == 'production' }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "상용 배포가 완료되었습니다!"
          avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
