name: Pull Request Notification For Discord

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PR Open/Reopen Discord Notification 
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_AVATAR: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        with:
          args: |
            Pull Request가 생성되었습니다!
            **Title:** ${{ github.event.pull_request.title }}
            **Description:** ${{ github.event.pull_request.body }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **Link:** ${{ github.event.pull_request.html_url }}
          

      - name: PR Merged Discord Notification 
        if: github.event.pull_request.merged == true
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_AVATAR: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        with:
          args: |
            Pull Request가 머지되었습니다!
            **Title:** ${{ github.event.pull_request.title }}
            **Description:** ${{ github.event.pull_request.body }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **Merged by:** ${{ github.event.actor.login }}
            **Link:** ${{ github.event.pull_request.html_url }}